import {StyleSheet} from 'react-native';
import {resize} from './utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    height: resize(740),
    backgroundColor: '#f8f8f8',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 15,
    marginTop: 15,
  },
  headerText: {
    fontWeight: '800',
    fontSize: 17,
    textTransform: 'capitalize',
    fontFamily: 'NormExBold',
    letterSpacing: 0.5,
    color: '#050505',
  },
  imageBackground: {
    height: 200,
  },
  headingBlock: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderBottomColor: '#ebedec',
    borderBottomWidth: 1,
  },
  roomTitle: {
    fontSize: 17,
    fontFamily: 'NormExBold',
    letterSpacing: 0.5,
    color: '#050505',
    fontWeight: '700',
    marginBottom: resize(10),
  },
  tagFlex: {flexDirection: 'row', flexWrap: 'wrap'},
  tagItem: {
    color: '#5e586e',
    textTransform: 'capitalize',
    marginRight: 8,
    fontFamily: 'NormDemi',
    fontWeight: '600',
  },
  activity: {
    paddingHorizontal: 10,
    borderBottomColor: '#ebedec',
    borderBottomWidth: 1,
  },
  activityBlockTitle: {
    paddingTop: resize(10),
    fontSize: 17,
    textTransform: 'capitalize',
    fontFamily: 'NormExBold',
    letterSpacing: 0.5,
    color: '#050505',
    fontWeight: '700',
    marginBottom: resize(10),
  },
  activityInfo: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
  },
  activityInfoText: {
    marginLeft: 10,
    fontFamily: 'NormDemi',
    fontSize: 12,
  },
  rule: {flexDirection: 'row', marginBottom: resize(10)},
  ruleContent: {marginLeft: resize(8), width: '90%'},
  ruleMore: {marginLeft: 'auto'},
  fixedOverlay: {
    position: 'absolute',
    display: 'flex',
    height: resize(74),
    bottom: 0,
    backgroundColor: '#FFF',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
  },
  joinRoomButton: {
    backgroundColor: '#0c7962',
    height: resize(45),
    width: resize(310),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  joinRoomButtonText: {
    color: '#FEFEFE',
  },
  text: {
    lineHeight: 20,
    fontFamily: 'NormBook',
    color: '#000',
    fontSize: 12,
  },
  rulesHeader: {
    lineHeight: 20,
    fontFamily: 'NormExBold',
    color: '#000',
    fontSize: 13,
    fontWeight: '700',
  },
});
